# Generated by Django 2.2.18 on 2021-05-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fecha_accidente',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('rfc',), name=''),
        ),
    ]
